sudo: required
language: php
services:
    - nodejs
    - phantomjs
before_install:
    - cd test
    - mkdir ../../js
    - cp __config.js ../../js/config.js
    - touch ../../authenticate.php
    - cp test/_config.php ../../config.php
    - cp test/_config.ini ../../config.ini
    - which php
install:
    - npm install
    - npm install -g casperjs
before_script:
    - node test_server.js &
script:
    - casperjs test casper_test.js
