sudo: required
language: php
services:
    - nodejs
    - phantomjs
before_install:
    - cd test
    - mkdir ../../js
    - cp __config.js ../../js/config.js
    - touch ../../authenticate.php
    - mv _config.php /home/travis/.phpenv/versions/config.php
    - mv _config.ini /home/travis/.phpenv/versions/config.ini 
    - which php
install:
    - npm install
    - npm install -g casperjs
before_script:
    - node test_server.js &
script:
    - casperjs test casper_test.js
