sudo: required
language: php
services:
    - nodejs
    - phantomjs
before_install:
    - cd test
    - npm install
    - npm install -g casperjs
    - mkdir ../../js
    - cp __config.js ../../js/config.js
    - touch ../../authenticate.php
before_script:
    - node test_server.js &
script:
- casperjs test casper_test.js
