sudo: required
language: php
services:
    - nodejs
before_install:
    - mkdir ../js
    - cp __config.js ../js/config.js
    - touch ../authenticate.php
    - which php
install:
    - npm install
    - npm install -g mocha
before_script:
    - node test_server.js &
script:
    - mocha js --recursive
    - mocha test/functional_tests.js
